# Generated by Django 5.2.8 on 2026-01-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_customer_birth_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
