# Generated by Django 5.2.5 on 2025-08-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_address_zip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="given_name",
        ),
    ]
