# Generated by Django 5.2.5 on 2025-09-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
