# Generated by Django 6.0.1 on 2026-02-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
    ]
