# Generated by Django 5.2.5 on 2025-08-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_first_name_customer_given_name"),
    ]

    operations = [
        migrations.RunSQL(
            """
                INSERT INTO store_collection (title) VALUES ('collection1')
            """,
            """
                DELETE FROM store_collection WHERE title='collection1'
            """,
        )
    ]
